settings:
  initrepo:
    url: "https://github.com/haavard82/init.git"
  target_dir:
    path: ${HOME}/init
  xdg_config_home:
    path: ${HOME}/.config
  zdotdir:
    path: ${XDG_CONFIG_HOME}/zsh
  git_dir:
    path: ${XDG_CONFIG_HOME}/git
  git_api_url:
    url: "https://api.github.com/repos/nextcloud/desktop/releases/latest"
  brew_cmd:
    command: ${HOME}/homebrew/bin/brew
  log_file:
    path: ${HOME}/init.log
  init_template_marker_file:
    path: ${HOME}/.init_template_marker_file_ran

applications:
  - name: wireguard-go
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: wireguard-tools
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: zsh-autocomplete
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: zsh-syntax-highlighting
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: zsh-autosuggestions
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: jq
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: yq
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: brave-browser
    directory: "${HOME}/Applications/Brave Browser.app"
    type: "homebrew"
    method: "add"
  - name: iterm2
    directory: "${HOME}/Applications/iTerm.app"
    type: "homebrew"
    method: "add"
  - name: font-fontawesome
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: visual-studio-code
    directory: "${HOME}/Applications/Visual Studio Code.app"
    type: "homebrew"
    method: "add"
  - name: mattermost
    directory: "${HOME}/Applications/Mattermost.app"
    type: "homebrew"
    method: "add"
  - name: dockutil
    directory: "not specified"
    type: "homebrew"
    method: "none"
  - name: nextcloud
    directory: "${HOME}/Applications/Nextcloud.app"
    type: "native" # Native means that the application is not installed via homebrew
    method: "add"
  - name: "Apple Maps"
    directory: "/System/Applications/Maps.app"
    type: "native"
    method: "remove"
  - name: "Messages"
    directory: "/System/Applications/Messages.app"
    type: "native"
    method: "remove"
  - name: "Contacts"
    directory: "/System/Applications/Contacts.app"
    type: "native"
    method: "remove"
  - name: "Mail"
    directory: "/System/Applications/Mail.app"
    type: "native"
    method: "remove"
  - name: "FaceTime"
    directory: "/System/Applications/FaceTime.app"
    type: "native"
    method: "remove"
  - name: "Photos"
    directory: "/System/Applications/Photos.app"
    type: "native"
    method: "remove"
  - name: "TV"
    directory: "/System/Applications/TV.app"
    type: "native"
    method: "remove"
  - name: "Music"
    directory: "/System/Applications/Music.app"
    type: "native"
    method: "remove"
  - name: "Reminders"
    directory: "/System/Applications/Reminders.app"
    type: "native"
    method: "remove"
  - name: "Freeform"
    directory: "/System/Applications/Freeform.app"
    type: "native"
    method: "remove"

downloads:
  - name: HaX0R_GR33N_itermcolors
    source: "https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/HaX0R_GR33N.itermcolors"
    destination: "${XDG_CONFIG_HOME}/iterm2/HaX0R_GR33N.itermcolors"

init_list:
  - name: com.admin.init-user.plist
    source: "${TARGET_DIR}/launchagents/com.admin.init-user.plist"
    destination: "${HOME}/Library/LaunchAgents/com.admin.init-user.plist"
    permissions: "644"
  - name: com.admin.backup.plist
    source: "${TARGET_DIR}/launchagents/com.admin.backup.plist"
    destination: "${HOME}/Library/LaunchAgents/com.admin.backup.plist"
    permissions: "644"
  - name: zsh
    source: "${TARGET_DIR}/zsh"
    destination: "${ZDOTDIR}"
    permissions: "700"
  - name: wallpaper
    source: "${TARGET_DIR}/wallpaper/wallpaper_test.png"
    destination: "${HOME}/Pictures/wallpaper_test.png"
    permissions: "644"

vscode-extensions:
  - name: github.copilot
  - name: github.copilot-chat
  - name: johnpapa.vscode-peacock
  - name: redhat.vscode-yaml
  - name: sergeyegorov.folder-color
  - name: yzane.markdown-pdf
  - name: yzhang.markdown-all-in-one
  - name: zainchen.json
